routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@home');

//'middleware' => 'auth'
Route::group(['prefix' => 'admin','namespace' => 'Admin','middleware'=>'auth'], function () {

    Route::get('no_permission','WelcomeController@butNoPermission');
    Route::get('/', 'WelcomeController@index');

    Route::resource('permission','PermissionController');


    Route::get('role/permission/{role}', 'RoleController@rolePermission')->name('role.permission')->middleware('permission:permission_role');
    Route::get('role/{role}/remove', 'RoleController@remove')->name('role.remove');
    Route::post('role/permission', 'RoleController@rolePermissionStore')->name('role.permission.store')->middleware('permission:permission_role');
    Route::resource('role','RoleController');


    Route::get('user/role/{user}', 'UserController@userRole')->name('user.role')->middleware('permission:role_user');
    Route::post('user/role', 'UserController@userRoleStore')->name('user.role.store')->middleware('permission:role_user');
    Route::get('user/{user}/avatar','UserController@avatar')->name('user.avatar');
    Route::post('user/{user}/avatar','UserController@avatarUpload')->name('user.avatarUpload');
    Route::get('user/change_my','UserController@changeMy')->name('user.change_my');
    Route::post('user/store_my','UserController@storeMy')->name('user.store_my');
    Route::resource('user','UserController');


});


Auth::routes();

resources/views/layouts/admin_template.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "" }} {{Config::get('system.sys_name').'@'.Config::get('system.sys_version')}}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ asset("/bower_components/adminLTE/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{{ asset("/css/font-awesome.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="{{ asset("/css/ionicons.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ asset("/bower_components/adminLTE/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ asset("/bower_components/adminLTE/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
@stack('cssFiles')
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
<div class="wrapper">

    <!-- Header -->
    @include('layouts.header')

    <!-- Sidebar -->
    @include('layouts.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $page_title or "" }}
                <small>{{ $page_description or null }}</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('layouts.footer')

</div><!-- ./wrapper -->



<script src="{{ asset ('/bower_components/adminLTE/plugins/jQuery/jQuery-2.2.3.min.js') }}"></script>
<script src="{{ asset ('/bower_components/adminLTE/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ asset ('/bower_components/adminLTE/dist/js/app.min.js') }}" type="text/javascript"></script>
@stack('scriptFiles')
@stack('runningScripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'DFCMS') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        {{Config::get('system.sys_name')}} @ dev branch , page generated at {{date('Y-m-d H:i:s')}}
    </div>
    <!-- Default to the left -->
    <strong>Copyright © {{date('Y')}} .</strong>
</footer>

resources/views/layouts/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="javascript:;" class="logo"><b>DF</b>CMS</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{\Auth::user()->avatar}}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{\Auth::user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{\Auth::user()->avatar}}" class="img-circle" alt="User Image" />
                            <p>
                                {{\Auth::user()->name}} - @foreach(\Auth::user()->roles as $role) [{{$role->name}}]  @endforeach
                                <small>{{\Auth::user()->created_at}}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{route('user.change_my')}}" class="btn btn-primary btn-flat">个人信息</a>
                            </div>
                            <div class="pull-right">
                                <a onclick="event.preventDefault();document.getElementById('logout-form').submit();" href="{{route('logout')}}" class="btn btn-primary btn-flat">退出</a>

                                {!! Form::open(['route' => 'logout','id'=>'logout-form','style'=>'display: none;','onclick'=>'event.preventDefault();document.getElementById("logout-form").submit();']) !!}
                                {!! Form::close() !!}
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">

                <img src="{{\Auth::user()->avatar}}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{\Auth::user()->name}}</p>
                <!-- Status -->

            </div>
        </div>



        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li  class="treeview {{ active_class(if_route_pattern(['permission.*','role.*','user.*'])) }}">
                <a href="#"><span>系统设置</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li class="{{ active_class(if_route_pattern('permission.*')) }}"><a href="{{route('permission.index')}}">系统模块</a></li>
                    <li class="{{ active_class(if_route_pattern('role.*')) }}"><a href="{{route('role.index')}}">系统角色</a></li>
                    <li class="{{ active_class(if_route_pattern('user.*')) }}"><a href="{{route('user.index')}}">系统用户</a></li>
                </ul>
            </li>
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>